#!  /usr/local/bin/python3
import heapq

def heapsort(lst):
    h = []
    for el in lst:
        heapq.heappush(h, el)
    return [ heapq.heappop(h) for x in range(len(lst))]

def test():
    inps = [ [6,2,9,4], [12, 53, 8, 2, 100, 7]]
    expected = [ [2,4,6,9], [2, 7, 8, 12, 53,  100 ]]
    for x,y in zip(inps, expected):
        assert( heapsort(x) == y)

if __name__ == '__main__':
    test()


